language: R
cache: packages

script:
- Rscript -e 'rmarkdown::render("index.Rmd")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
